# Configuration file for Alacritty
# For more documentation: https://github.com/alacritty/alacritty

import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

# Shell
[env]
SHELL = "/bin/zsh"

# Shell program to use
#[shell]
#program = "/bin/zsh"
#args = ["-l", "-c", "/opt/homebrew/bin/tmux attach || /opt/homebrew/bin/tmux new"]

# Window settings
[window]
decorations = "Full"
# startup_mode = "Fullscreen"
dynamic_padding = true

#[window.padding]
#x = 5
#y = 5

# Font configuration
[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
size = 13.0

# Scrollback buffer
[scrolling]
history = 5000

