#!/usr/bin/env zsh
CWD=$(pwd)
SCRIPTPATH=$(cd -- "$(dirname "$0")" >/dev/null 2>&1; pwd -P)

# Existing zshrc files before installation
if [ -f ~/.zshrc ]; then
    mv ~/.zshrc ~/.zshrc.orig
fi

# Install gitstatus plugins
git clone --depth=1 https://github.com/romkatv/gitstatus.git ~/.gitstatus
ln -s ~/.gitstatus/gitstatus.prompt.zsh $SCRIPTPATH/zshrc.d/gitstatus.prompt.zsh
ln -s ~/.gitstatus/gitstatus.plugin.zsh $SCRIPTPATH/zshrc.d/gitstatus.plugin.zsh

# Create symlinks
ln -sf $SCRIPTPATH/zshrc ~/.zshrc
ln -sf $SCRIPTPATH/zshrc.d ~/.zshrc.d
ln -sf $SCRIPTPATH/bin ~/bin
ln -sf $SCRIPTPATH/git/gitconfig ~/.gitconfig
ln -sf $SCRIPTPATH/git/gitignore_global ~/.gitignore

# Setup neovim and lvim
NVIM=1
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Linux detected. Installing nvim.."
    sudo apt-get install neovim
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macOS (OSX) detected. Installing nvim.."
    brew install neovim
else
    echo "Unknown operating system."
    NVIM=0
fi

if [[ "$NVIM" -eq 1 ]]; then
    bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
fi

cd $CWD
